language: node_js
node_js:
  - node
  - lts/*
sudo: false
script:
  - npm run lint
  - npm run type
  - npm test
after_script:
  - npx nyc report --reporter=text-lcov | npx coveralls
stages:
- test
- deploy
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      deploy:
        provider: npm
        on:
          tags: true
        edge: true # opt in to dpl v2
